-- Expand fuel_records table
ALTER TABLE fuel_records 
ADD COLUMN IF NOT EXISTS unit_id UUID REFERENCES units(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS cost_per_liter DECIMAL(10, 3),
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS cost_center VARCHAR(100),
ADD COLUMN IF NOT EXISTS fleet_card VARCHAR(100),
ADD COLUMN IF NOT EXISTS receipt_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS uf VARCHAR(2);
